package com.mottmacdonald.android;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REPORT.
 */
public class Report {

    private Long id;
    /** Not-null value. */
    private String inspectionDate;
    private String time;
    private String environmentalPermitNo;
    private String siteLocation;
    private String pm;
    private String et;
    private String contractor;
    private String iec;
    private String others;
    private String contractNumber;
    private String contractId;
    private String saveDate;
    private String formId;
    private java.util.Date date;

    public Report() {
    }

    public Report(Long id) {
        this.id = id;
    }

    public Report(Long id, String inspectionDate, String time, String environmentalPermitNo, String siteLocation, String pm, String et, String contractor, String iec, String others, String contractNumber, String contractId, String saveDate, java.util.Date date) {
        this.id = id;
        this.inspectionDate = inspectionDate;
        this.time = time;
        this.environmentalPermitNo = environmentalPermitNo;
        this.siteLocation = siteLocation;
        this.pm = pm;
        this.et = et;
        this.contractor = contractor;
        this.iec = iec;
        this.others = others;
        this.contractNumber = contractNumber;
        this.contractId = contractId;
        this.saveDate = saveDate;
        this.date = date;
    }

    public String getFormId() {
        return formId;
    }

    public void setFormId(String formId) {
        this.formId = formId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getInspectionDate() {
        return inspectionDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInspectionDate(String inspectionDate) {
        this.inspectionDate = inspectionDate;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getEnvironmentalPermitNo() {
        return environmentalPermitNo;
    }

    public void setEnvironmentalPermitNo(String environmentalPermitNo) {
        this.environmentalPermitNo = environmentalPermitNo;
    }

    public String getSiteLocation() {
        return siteLocation;
    }

    public void setSiteLocation(String siteLocation) {
        this.siteLocation = siteLocation;
    }

    public String getPm() {
        return pm;
    }

    public void setPm(String pm) {
        this.pm = pm;
    }

    public String getEt() {
        return et;
    }

    public void setEt(String et) {
        this.et = et;
    }

    public String getContractor() {
        return contractor;
    }

    public void setContractor(String contractor) {
        this.contractor = contractor;
    }

    public String getIec() {
        return iec;
    }

    public void setIec(String iec) {
        this.iec = iec;
    }

    public String getOthers() {
        return others;
    }

    public void setOthers(String others) {
        this.others = others;
    }

    public String getContractNumber() {
        return contractNumber;
    }

    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }

    public String getContractId() {
        return contractId;
    }

    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    public String getSaveDate() {
        return saveDate;
    }

    public void setSaveDate(String saveDate) {
        this.saveDate = saveDate;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
