package com.mottmacdonald.android;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WEATHER.
 */
public class Weather {

    private Long id;
    /** Not-null value. */
    private String condition;
    private String temperature;
    private String humidity;
    private String wind;
    private String remarks;
    private String saveDate;
    private java.util.Date date;

    public Weather() {
    }

    public Weather(Long id) {
        this.id = id;
    }

    public Weather(Long id, String condition, String temperature, String humidity, String wind, String remarks, String saveDate, java.util.Date date) {
        this.id = id;
        this.condition = condition;
        this.temperature = temperature;
        this.humidity = humidity;
        this.wind = wind;
        this.remarks = remarks;
        this.saveDate = saveDate;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCondition() {
        return condition;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCondition(String condition) {
        this.condition = condition;
    }

    public String getTemperature() {
        return temperature;
    }

    public void setTemperature(String temperature) {
        this.temperature = temperature;
    }

    public String getHumidity() {
        return humidity;
    }

    public void setHumidity(String humidity) {
        this.humidity = humidity;
    }

    public String getWind() {
        return wind;
    }

    public void setWind(String wind) {
        this.wind = wind;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getSaveDate() {
        return saveDate;
    }

    public void setSaveDate(String saveDate) {
        this.saveDate = saveDate;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
